services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aone
      MYSQL_USER: admin
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - 3306
